[ui]
is_visible = 1
label = Splunk License Size Estimator

[launcher]
author = Vatsal Jagani
description = A tool to estimate Splunk license size based on your environment configuration
version = 1.0.0

[package]
check_for_updates = 1
id = splunk_license_size_estimator

[install]
is_configured = 0
